### ISSUE TITLE
Use improved string formatting

### ISSUE THREAD

**Issue by sudzhaev** [Sobieg/CryptoLabs#1]
https://github.com/Sobieg/CryptoLabs/blob/0a84f215cb22b7f336ee4903026192c220daf489/schemeinstall.py#L29

new versions of python provide more readable solution to string formatting
https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python

**Comment by Sobieg** [comment]
Resolved in https://github.com/Sobieg/CryptoLabs/commit/2be417e3e1902f1d8214a4f75dfc283f1ec6b25f
